### PR TITLE
Started creating Documenter.jl based documentation

### PR DESCRIPTION
**Pull request by mehalter**
I noticed you opened an issue about creating Documenter.jl documentation (#33). I figured I could help pick up some of the leg work to get started. All it contains is the Module APIs and the index contains the contents of the README so far.

I also added a travis job to build the documentation on pushes, and there is commented out code in the `doc/make.jl` that will enable pushing the generated HTML to a `gh_pages` branch.

### CODE REVIEW

**Comment by epatters** [comment]
Thank you! This is very helpful.

One comment. Regular users of the package shouldn't have to install Documenter. We should be able to do this without adding Documenter to the project or manifest files. For example, LightGraphs seems to have done this ([.travis.yml](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/.travis.yml) and [Project.toml](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/Project.toml)).

**Comment by mehalter** [comment]
Yeah that is a good point, I can make these changes.

**Comment by mehalter** [comment]
Ok, these changes have been made

**Comment by epatters** [comment]
Perfect, thanks. I will set up deployment of the docs later.

**Pull request merged**
